spring:
  redis:
    host: 127.0.0.1
    port: 6379
    #    password: 123456
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
